apiVersion: v1
kind: Service
metadata:
  name: aks-store-demo-workflow
  namespace: aks-store-demo
  labels:
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app: aks-store-demo-workflow
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000